sudo: required
services:
  - docker

before_install:
  - docker build -t bsikute/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bsikute/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "React-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-586825010029"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"